//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takhfifan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int ID { get; set; }
        public Nullable<int> commentID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
        public string commentText { get; set; }
    
        public virtual User User { get; set; }
    }
}
