//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Takhfifan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Price { get; set; }
        public string startDate { get; set; }
        public string endDate { get; set; }
        public Nullable<double> offPercent { get; set; }
        public string Feature { get; set; }
        public string useCondition { get; set; }
        public string responseTime { get; set; }
        public string serviceDate { get; set; }
        public string Tell { get; set; }
        public string Address { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Pic { get; set; }
        public string menuPic { get; set; }
        public Nullable<int> categoryID { get; set; }
        public Nullable<int> cityID { get; set; }
    }
}
